<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\Ico.ico</ApplicationIcon>
        <AssemblyVersion>1.0.0.1</AssemblyVersion>
        <FileVersion>1.0.0.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LiveChartsCore" Version="2.0.0-rc4.5" />
        <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc4.5" />
        <PackageReference Include="MessagePack" Version="3.1.1" />
        <PackageReference Include="Microsoft.Win32.SystemEvents" Version="9.0.0" />
        <PackageReference Include="ReactiveUI.WPF" Version="20.1.63" />
        <PackageReference Include="SkiaSharp" Version="3.118.0-preview.2.3" />
        <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.0" />
        <PackageReference Include="System.Management" Version="9.0.0" />
        <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Assets\Ico.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
</Project>
